Aufgaben PyTorch
================



## Install PyTorch



Checkout this website, to obtain the command to install Pytorch:
[https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/)

Check the version



In [32]:
import numpy as np
import math 
import torch
print(f'Version {torch.__version__}')

Version 2.0.1


and run some code:



In [16]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7913, 0.7845, 0.9869],
        [0.5844, 0.5782, 0.8301],
        [0.2970, 0.2336, 0.0685],
        [0.0508, 0.0734, 0.2850],
        [0.7956, 0.0433, 0.4205]])


## Shapes



1.  Create a tensor `a` from a list with 9 elements (e.g, `range(9)`). Predict and then check the shape (size).

2.  Create a new tensor using `b = a.view(3, 3)`. What does view do? Check that a and b share the same storage.

3.  Create a tensor `c = b[1:, 1:]`. Predict and then check the shape.



In [30]:
a = torch.tensor(range(9))
print(a)
print(a.shape)

b = a.view(3, 3)
print(b)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([ 0,  1,  2,  3,  4, 90,  6,  7,  8])
tensor([[ 0,  1,  2],
        [ 3,  4, 90],
        [ 6,  7,  8]])


## Broadcasting



Predict and check the result of the following operation:



In [31]:
a = torch.tensor(range(9)).reshape(3,3)
b = torch.tensor([1, 1, 1])

print(a+b)


# 0 1 2     1 1 1     1 2 3
# 3 4 5  +         =  4 5 6     
# 6 7 8               7 8 9

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


Can you  explain the observed behaviour?



## Sharing between NumPy and PyTorch



Create a random `numpy` array (for example with `numpy.random.normal`) of shape (4,3).
Now create a bridged torch tensor (`from_numpy`).
Show that multiplying the torch tensor with some number, also change `a`.
Hint: to multiply in place use `mul_`.



In [45]:
np_array = np.reshape(np.random.normal(size=4*3), (4, 3))
torch_tensor = torch.from_numpy(np_array)

print(np_array)
print(torch_tensor)

torch_tensor.mul_(4)

print(np_array)
print(torch_tensor)


[[ 2.36252288  0.36552367 -1.31363679]
 [ 0.35500841 -0.55681937  0.79027718]
 [-0.71161129  1.78668213 -0.52029969]
 [-0.47125404 -0.51014877  2.07629081]]
tensor([[ 2.3625,  0.3655, -1.3136],
        [ 0.3550, -0.5568,  0.7903],
        [-0.7116,  1.7867, -0.5203],
        [-0.4713, -0.5101,  2.0763]], dtype=torch.float64)
[[ 9.45009151  1.46209469 -5.25454718]
 [ 1.42003365 -2.22727748  3.1611087 ]
 [-2.84644516  7.14672853 -2.08119876]
 [-1.88501615 -2.04059509  8.30516326]]
tensor([[ 9.4501,  1.4621, -5.2545],
        [ 1.4200, -2.2273,  3.1611],
        [-2.8464,  7.1467, -2.0812],
        [-1.8850, -2.0406,  8.3052]], dtype=torch.float64)


## Autograd



For $x=1$ compute the following
$$
\frac{d}{d x} f(h(x))
$$
where $f(x) = x^3$ and $h(x)=cos(x)$.

1.  First compute the result by *hand* (use the chain rule, and a calculator)
2.  Write a Python script to compute it with PyTorch using  `autograd`.



In [53]:
def h(x):
    return torch.cos(x)

def f(x):
    return x**3

x = torch.tensor(1.0, requires_grad=True)
y = f(h(x))
y.backward()
print(x.grad)

tensor(-0.7369)
